### ISSUE TITLE
Connect-MgGraph : AADSTS70000: The provided value for the input parameter 'device_code' is not valid.

### ISSUE THREAD

**Issue by ryanspletzer** [microsoftgraph/msgraph-sdk-serviceissues#33]
Anyone else noticing this? I'm seeing it on multiple machines, re-installed the Graph modules to troubleshoot but still persists. Cert-based auth still works, but device code flow doesn't.

![image](https://user-images.githubusercontent.com/1481108/98831252-4f611480-2409-11eb-836f-720947e81ea7.png)

**Comment by ryanspletzer** [comment]
Probably can close this, yeah?

**Comment by peombwa** [comment]
Thanks @ryanspletzer!! Closing since this has now been fixed.
