### ISSUE TITLE
Retrieve the count using the PageIterator class?

### ISSUE THREAD

**Issue by plamber** [microsoftgraph/msgraph-sdk-serviceissues#38]
# Feature Request
I am looking for a way to retrieve from the PageIterator class the count of records returned in case of a "count()" query operation.

Lets consider a query that returns the groups.

`
....
let response: PageCollection = await client
        .api("/groups")
        .select("id,displayName,description,mail,groupTypes")
        .orderby("displayName")
        .count(true)
        .get();

return new PageIterator(client, response, callback)
`

I haven't found a way to get the count returned by the Graph call of the query above. Would it be possible to expose this property in the PageIterator class? This option might be useful when showing total results in a table to a user.

Thank you for your feedback,
Patrick

**Comment by plamber** [comment]
Hi @nikithauc,
the Group Graph Response returns the count in the header information. At least I am able to see it. 

The problem I am facing is that this information is not exposed in the PageIterator class. At least I haven't found how to retrieve this information from there.

Thank you for your feedback

**Comment by MIchaelMainer** [comment]
@plamber How did you get the count information in a group response? I try it and do not get the count in either the response body or headers. Can you give me your repro instructions? Can you repro with Graph Explorer?

https://developer.microsoft.com/en-us/graph/graph-explorer?request=groups%3F%24select%3Did%2CdisplayName%2Cdescription%2Cmail%2CgroupTypes%26%24orderby%3DdisplayName%26%24count%3Dtrue&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com

Can you explain how accessing **count** information from the headers or body is useful for your scenario?

**Comment by plamber** [comment]
@MIchaelMainer
I am not using Graph explorer to verify this. I run the code with this project's sdk and can reproduce it from there.

I am initiating the Graph client with consistencyLevel: 'eventual'. I need it to perform the complex query below:
```fetchOptions: { headers: { ConsistencyLevel: 'eventual' } }```

Then a Graph call using this syntax.
```client
        .api("/groups")
        .select("id,displayName,description,mail,groupTypes")
        .filter("groupTypes/any(c:c+eq+'Unified')")
        .orderby("displayName").top(15)
        .count(true)
        .get();
```
It results in this query.
```
GET
https://graph.microsoft.com/v1.0/groups?$select=id,displayName,description,mail,groupTypes&$filter=groupTypes/any(c:c eq 'Unified')&$top=15&$count=true
ConsistencyLevel: 'eventual'
```

When looking at the response header I can see an @odata.count. It is the count of the Groups from my query.
![image](https://user-images.githubusercontent.com/18241305/101446725-1a6eb180-3924-11eb-9669-8a6d6df246c5.png)

**Comment by nikithauc** [comment]
@plamber
@odata.count is available when the first request is made with the ConsistencyLevel: 'eventual' header. However, it doesn't appear that the count parameter is being returned by the API when the url in the @odata.nextlink is called.

A workaround that I suggest is you could capture the total count when making the first request and then work with a counter in your callback function if that is possible.

**Comment by plamber** [comment]
Hi,
Do you have a suggestion how to achieve this with the sdk?

I am planning to use the iterator and havent found a way to get the header variables

Thank you for your suggestion

Br

**Comment by nikithauc** [comment]
Do you want the total count of the all events at once  or the count when when everytime the 'odata.nextLink' is called?  

To access the values in headers, I would suggest to try setting ResponseType as RAW -> https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/GettingRawResponse.md and then access the response headers.

**Comment by plamber** [comment]
@nikithauc thank you. Will give it a try
